- name: Check if Kubernetes nodes are ready
  shell: kubectl get nodes --no-headers | awk '{print $2}' | grep -v "Ready"
  register: node_check
  until: node_check.stdout_lines | length == 0
  retries: 60
  delay: 10
  ignore_errors: true

- name: Wait for kubernetes api port
  wait_for:
    timeout: 300 
    port: 6443  
    state: started
    delay: 10

- name: Get deployments in kube-system namespace
  shell: |
    deployments=$(kubectl get deploy -n kube-system -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.status.unavailableReplicas}{'\n'}{end}")
    while read -r line; do lines+=("$line"); done <<<"$deployments"
    for line in "${lines[@]}"
    do
      read -ra arr <<< "$line"
      if [ "${arr[1]}" ]; then
        echo "${arr[0]} deployment has ${arr[1]} unavailable Replicas "
      fi
    done




# - name: Add a certmanager helm repository
#   kubernetes.core.helm_repository:
#     name: jetstack
#     repo_url: https://charts.jetstack.io

# - name: Install certmanager
#   kubernetes.core.helm:
#     name: cert-manager
#     chart_ref: jetstack/cert-manager
#     release_namespace: cert-manager
#     create_namespace: true
#     update_repo_cache: true
#     values:
#       installCRDs: true

# - name: Add a rancher helm repository
#   kubernetes.core.helm_repository:
#     name: rancher-latest
#     repo_url: https://releases.rancher.com/server-charts/latest

# - name: Install rancher
#   kubernetes.core.helm:
#     name: rancher
#     chart_ref: rancher-latest/rancher
#     release_namespace: cattle-system
#     create_namespace: true
#     update_repo_cache: true
#     values:
#       hostname: "{{rancher_hostname}}"
#       bootstrapPassword: "{{rancher_admin_password}}"
