- name: Check if Kubernetes nodes are ready
  shell: kubectl get nodes --no-headers | awk '{print $2}' | grep -v "Ready"
  register: node_check
  until: node_check.stdout_lines | length == 0
  retries: 60
  delay: 10
  ignore_errors: true

- name: Wait for kubernetes api port
  wait_for:
    timeout: 300 
    port: 6443  
    state: started
    delay: 10

- name: Get all deployments in the namespace
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: kube-system
  register: deployments_info

- name: Wait until all deployments are ready
  block:
    - name: Check if all deployments are ready
      set_fact:
        ready_deployments: "{{ deployments_info.resources | selectattr('status.conditions', 'equalto', [{'type': 'Available', 'status': 'True'}]) | map(attribute='metadata.name') | list }}"
    - name: Wait for deployments to be ready
      kubernetes.core.k8s_wait:
        kind: Deployment
        name: "{{ item }}"
        namespace: your_namespace
        timeout: 300
        wait_condition:
          type: Available
          status: "True"
      loop: "{{ ready_deployments }}"
      retries: 20
      delay: 15
  when: ready_deployments | length > 0


# - name: Add a certmanager helm repository
#   kubernetes.core.helm_repository:
#     name: jetstack
#     repo_url: https://charts.jetstack.io

# - name: Install certmanager
#   kubernetes.core.helm:
#     name: cert-manager
#     chart_ref: jetstack/cert-manager
#     release_namespace: cert-manager
#     create_namespace: true
#     update_repo_cache: true
#     values:
#       installCRDs: true

# - name: Add a rancher helm repository
#   kubernetes.core.helm_repository:
#     name: rancher-latest
#     repo_url: https://releases.rancher.com/server-charts/latest

# - name: Install rancher
#   kubernetes.core.helm:
#     name: rancher
#     chart_ref: rancher-latest/rancher
#     release_namespace: cattle-system
#     create_namespace: true
#     update_repo_cache: true
#     values:
#       hostname: "{{rancher_hostname}}"
#       bootstrapPassword: "{{rancher_admin_password}}"
