- name: "create directory for project"
  file:
    path: "{{ vault_root_dir }}/vaultbuild"
    state: directory
    recurse: yes

- name: "deploy vault Dockerfile"
  template:
    src: "../templates/Dockerfile.j2"
    dest: "{{ vault_root_dir }}/vaultbuild/Dockerfile"
  notify: Restart Vault

- name: "deploy systemd service"
  template:
    src: "../templates/vault.service.j2"
    dest: "/etc/systemd/system/vault.service"
  notify: Restart Vault

- name: "deploy init script"
  template:
    src: "../templates/init.sh.j2"
    dest: "{{ vault_root_dir }}/vaultbuild/init.sh"
    mode: 0755
  notify: Restart Vault

- name: "deploy vault-config.hcl"
  template:
    src: "../templates/vault-config.hcl.j2"
    dest: "{{ vault_root_dir }}/vault-config.hcl"
  notify: Restart Vault

- name: "deploy docker compose file"
  template:
    src: "../templates/vault.docker-compose.yml.j2"
    dest: "{{ vault_root_dir }}/docker-compose.yml"
  notify: Restart Vault

- name: "set to auto restart"
  systemd:
    enabled: true
    daemon_reload: true
    name: "vault"
    state: started
