- name: "Copy deployment check script"
  copy:
    src: "check_deployment.sh"
    dest: "/root/check_deployment.sh"
    mode: "0755"

- name: Add a daas helm repository
  kubernetes.core.helm_repository:
    name: daas
    repo_url: https://oci-sunbird.github.io/daas-helm

- name: Add a longhorn helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Add a cloud native postgres helm repository
  kubernetes.core.helm_repository:
    name: cnpg
    repo_url: https://cloudnative-pg.github.io/charts

- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /root/sunbird-rc/customization
    - /root/sunbird-rc/customization/longhorn
    - /root/sunbird-rc/customization/postgres

- name: Create a k8s namespace for sunbird-rc
  kubernetes.core.k8s:
    name: sunbird-rc
    api_version: v1
    kind: Namespace
    state: present

