- name: Install Postgres
  kubernetes.core.helm:
    name: cnpg
    chart_ref: cnpg/cloudnative-pg
    chart_version: 0.19.0
    release_namespace: cnpg-system
    create_namespace: true
    update_repo_cache: true

- name: Wait for deployments in cnpg-system namespace
  shell: bash /root/check_deployment.sh cnpg-system

- name: "Update postgres db config"
  template:
    src: "postgres/postgres.yaml.j2"
    dest: "/root/sunbird-rc/customization/postgres/postgres.yaml"

- name: Create postres db
  shell: |
    kubectl -n sunbird-rc apply -f /root/sunbird-rc/customization/postgres/postgres.yaml

