
- include_tasks: common.yaml
# - include_tasks: update_zone_record.yaml
# - include_tasks: install_longhorn.yaml
- include_tasks: install_postgres.yaml
# - include_tasks: install_certificateapi.yaml

