- name: Get Deployment status
  shell: |
    kubectl get pods --all-namespaces
  regsiter: deployment_results

- name: Show Deployment status
  debug: 
    msg: '{{deployment_results.stdout}}'


- name: "Create Outputs"
  template:
    src: "outputs.j2"
    dest: "/root/sunbird-rc/customization/outputs/outputs.txt"
    mode: "0600"

- name: Fetch file from remote server
  fetch:
    src: "/root/sunbird-rc/customization/outputs/outputs.txt"
    dest: "{{ inventory_dir }}/"
    flat: yes