- name: "Create Outputs"
  template:
    src: "outputs.j2"
    dest: "/root/sunbird-rc/customization/outputs/outputs_{{domain}}.txt"
    mode: "0600"

- name: Fetch file from remote server
  fetch:
    src: "/root/sunbird-rc/customization/outputs/outputs_{{domain}}.txt"
    dest: "{{ inventory_dir }}/"
    flat: yes