- name: Pull Docker image
  community.docker.docker_image:
    name: "{{ container_image }}"
    source: pull

- name: Create a volume
  community.docker.docker_volume:
    name: "{{ volume_name }}"
    state: present

- name: Create containers
  community.docker.docker_container:
    name: "{{ container_name }}"
    container_default_behavior: compatibility
    image: "{{ container_image }}"
    state: started
    ports:
      - "8081:8081"
      - "{{ nexus_docker_repo_listening_port }}:{{ nexus_docker_repo_listening_port }}"
    volumes:
      - "{{ volume_name }}:/{{ volume_name }}"
    restart_policy: always 