- hosts: bastion
  become: true
  environment:
    KUBECONFIG: "/root/.kube/oke_obs_config"
  roles:
    - sunbird-rc.iac.rancher_oke_deploy

- hosts: bastion
  become: true
  environment:
    KUBECONFIG: "/root/.kube/oke_k8s_config"
  roles:
    - sunbird-rc.iac.rancher_oke_import_cluster