- name: Add a rancher helm repository
  kubernetes.core.helm_repository:
    name: rancher-latest
    repo_url: https://releases.rancher.com/server-charts/latest

- name: Install rancher
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-latest/rancher
    release_namespace: cattle-system
    create_namespace: true
    update_repo_cache: true
    values:
      hostname: "{{rancher_hostname}}"
      bootstrapPassword: "{{rancher_admin_password}}"

- name: Get deployments in cattle-system namespace
  shell: bash /root/check_deployment.sh cattle-system 