- name: "Copy deployment check script"
  copy:
    src: "check_deployment.sh"
    dest: "/root/check_deployment.sh"
    mode: "0755"

- name: Clone OpenG2P Deployment Repo
  ansible.builtin.git:
    repo: https://github.com/OpenG2P/openg2p-deployment.git
    dest: /root/openg2p-deployment
    single_branch: yes
    version: main

- name: Clone MOSIP infra Deployment Repo
  ansible.builtin.git:
    repo: https://github.com/mosip/mosip-infra.git
    dest: /root/mosip-infra
    single_branch: yes
    version: v1.2.0.1

- name: Add a mosip helm repository
  kubernetes.core.helm_repository:
    name: mosip
    repo_url: https://mosip.github.io/mosip-helm

- name: Create customization directory
  file:
    path: "/root/openg2p/customization"
    state: directory
    mode: '0755'