- name: "Copy deployment check script"
  copy:
    src: "check_deployment.sh"
    dest: "/root/check_deployment.sh"
    mode: "0755"

- name: Add a mosip helm repository
  kubernetes.core.helm_repository:
    name: mosip
    repo_url: https://mosip.github.io/mosip-helm

- name: Create config server directory
  file:
    path: "/root/mosip/config-server"
    state: directory
    mode: '0755'

# - name: "Copy deployment check script"
#   copy:
#     src: "{{ item }}"
#     dest: "/root/mosip/config-server/{{ item }}"
#     mode: "0755"
#     with_items:
#       - copy_cm_func.sh
#       - copy_cm.sh
#       - copy_secrets.sh
#       - install.sh
#       - values.yaml

- name: copy files
  copy:
    src: "{{ item }}.yaml"
    dest: "/root/mosip/config-server/{{ item }}.yaml"
  with_items:
    - values

# - name: Clone mosip infra Repo
#   ansible.builtin.git:
#     repo: https://github.com/mosip/mosip-infra.git
#     dest: /root/mosip-infra
#     single_branch: yes
#     version: v1.2.0.1


# - name: Install config server
#   shell: |
#     cd /root/mosip-infra/deployment/v3/mosip/config-server
#     ./install.sh