- name: "Copy deployment check script"
  copy:
    src: "check_deployment.sh"
    dest: "/root/check_deployment.sh"
    mode: "0755"

- name: Clone mosip infra Repo
  ansible.builtin.git:
    repo: https://github.com/mosip/mosip-infra.git
    dest: /root/mosip-infra
    single_branch: yes
    version: v1.2.0.1

