- name: Install istio operator
  shell: |
    export PATH=/root/istio-1.21.0/bin:$PATH
    istioctl operator init

- name: Create istio config directory
  file:
    path: "/root/kubernetes/istio"
    state: directory
    mode: '0755'

- name: "Update istio operator config"
  template:
    src: "istio-operator-external-lb.j2"
    dest: "/root/kubernetes/istio/istio-operator-external-lb.yaml"

- name: Install istio ingress gateway
  shell: kubectl apply -f /root/kubernetes/istio/istio-operator-external-lb.yaml

- name: "Update clusterissuer config"
  template:
    src: "cluster_issuer.j2"
    dest: "/root/kubernetes/istio/cluster_issuer.yaml"

- name: Install Cluster Issuer
  shell: kubectl apply -f /root/kubernetes/istio/cluster_issuer.yaml

- name: "Update certificate config"
  template:
    src: "certificate.j2"
    dest: "/root/kubernetes/istio/certificate.yaml"

- name: Install Certificate
  shell: kubectl apply -f /root/kubernetes/istio/certificate.yaml