- include_tasks: common.yaml
# - include_tasks: install_certmanager.yaml
# - include_tasks: install_istio_operator.yaml
# - include_tasks: install_postgres.yaml
- include_tasks: install_global_config.yaml
- include_tasks: install_config_server_secrets.yaml
- include_tasks: install_config_server.yaml
# - include_tasks: install_esignet.yaml
