# - name: Deploy ODK
#   shell: |
#     export SANDBOX_HOSTNAME={{domain}}
#     cd /root/sunbird-rc-deployment/kubernetes/odk-central
#     ./install.sh

- name: Copy Deploy folder
  shell: cp -r /root/sunbird-rc-deployment/kubernetes/ /root/sunbird-rc/customization/


- name: "Update odk config"
  template:
    src: "odk/install.j2"
    dest: "/root/sunbird-rc/customization/kubernetes/odk-central/install.sh"
    mode: '0755'


- name: Deploy ODK
  shell: |
    export SANDBOX_HOSTNAME={{domain}}
    kubens default
    cd /root/sunbird-rc/customization/kubernetes/odk-central
    ./install.sh

- name: Wait for deployments in odk namespace
  shell: bash /root/check_deployment.sh odk
