- name: Generate kube config for oke k8s cluster
  shell: |
    oci ce cluster create-kubeconfig --cluster-id {{oke_k8s_cluster_id}} --file /home/opc/.kube/config --region {{region}} --token-version 2.0.0  --kube-endpoint PRIVATE_ENDPOINT
    chmod 600 /home/opc/.kube/config

- name: Install kubernetes pre requisites
  pip:
    name: 
      - kubernetes

- name: Taint Nodes
  shell: |
    kubectl taint nodes -l oke.oraclecloud.com/pool.name=rook node-role.kubernetes.io/rook-node=true:NoSchedule --overwrite


- name: Get details of the node pool
  oracle.oci.oci_container_engine_node_pool_facts:
    compartment_id: "{{compartment_id}}"
    cluster_id: "{{oke_k8s_cluster_id}}"
    name: "rook"
  register: node_pool_fact

# - name: Extract instance OCIDs from node pool details
#   set_fact:
#     instance_ocids: "{{ node_pool_facts.data.node_pools[0].node_config_details[0].placement_configs | map(attribute='instance_id') | list }}"

- name: Display instance OCIDs
  debug:
    msg: "{{ node_pool_fact.node_pools[0].node_config_details.nodes }}"