# - name: Generate kube config for oke k8s cluster
#   shell: |
#     oci ce cluster create-kubeconfig --cluster-id {{oke_k8s_cluster_id}} --file /home/opc/.kube/config --region {{region}} --token-version 2.0.0  --kube-endpoint PRIVATE_ENDPOINT
#     chmod 600 /home/opc/.kube/config

# - name: Install kubernetes pre requisites
#   pip:
#     name: 
#       - kubernetes

# - name: Taint Nodes
#   shell: |
#     kubectl taint nodes -l oke.oraclecloud.com/pool.name=rook node-role.kubernetes.io/rook-node=true:NoSchedule --overwrite


- name: Get details of the node pool
  oracle.oci.oci_container_engine_node_pool_facts:
    compartment_id: "{{compartment_id}}"
    cluster_id: "{{oke_k8s_cluster_id}}"
    name: "rook"
  register: node_pool_fact

- name: Save node pool ocid
  set_fact:
    rook_node_pool_id: "{{ node_pool_fact.node_pools[0].id }}"

- name: Get node pool instance IDs
  shell: |
    oci ce node-pool get --node-pool-id {{rook_node_pool_id}} --query "data.nodes[*].id" --output json
  register: node_pool_output

- name: Parse instance IDs from output
  set_fact:
    instance_ids: "{{ node_pool_output.stdout | from_json }}"


- name: List availability_domains
  oracle.oci.oci_identity_availability_domain_facts:
    compartment_id: "{{compartment_id}}"
  register: ad_facts

- name: Store availability domain names in a variable
  set_fact:
    availability_domain_names: "{{ ad_facts.availability_domains | map(attribute='name') | list }}"

- name: Create block volumes for each instance
  oracle.oci.oci_blockstorage_volume:
    compartment_id: "{{compartment_id}}" 
    availability_domain: "{{availability_domain_names[0]}}"
    size_in_gbs: 50  # Specify the size of the block volume (in GB)
    display_name: "rook-{{ idx }}"
  with_items: "{{ instance_ids }}"
  loop_control:
    loop_var: item
    index_var: idx
  register: volume_creation


# - name: Debug
#   debug: 
#     var: "{{ volume_creation.results[0] }}"
#   with_items: "{{ instance_ids }}"
#   loop_control:
#     loop_var: item
#     index_var: idx  

- name: Debug volume creation output
  debug:
    var: "{{ volume_creation }}"
