- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /home/opc/rook

- name: Add a rook helm repository
  kubernetes.core.helm_repository:
    name: rook-release
    repo_url: https://charts.rook.io/release

- name: Install rook operator
  kubernetes.core.helm:
    name: rook-ceph
    chart_ref: rook-release/rook-ceph
    chart_version: "{{rook_operator_chart_version}}"
    release_namespace: rook-ceph
    create_namespace: true
    update_repo_cache: true
    wait: true
    values: 
      nodeSelector:
       oke.oraclecloud.com/pool.name: rook
      tolerations:
      - key: "node-role.kubernetes.io/rook-node"
        operator: "Exists"
        effect: "NoSchedule"
      csi:
        provisionerTolerations:
        - key: "node-role.kubernetes.io/rook-node"
          operator: "Exists"
          effect: "NoSchedule"
        provisionerNodeAffinity: 
          oke.oraclecloud.com/pool.name: rook
        pluginTolerations:
        - key: "node-role.kubernetes.io/rook-node"
          operator: "Exists"
          effect: "NoSchedule"
        pluginNodeAffinity: 
          oke.oraclecloud.com/pool.name: rook
      discover:
        tolerations:
        - key: "node-role.kubernetes.io/rook-node"
          operator: "Exists"
          effect: "NoSchedule"
        nodeAffinity:
          oke.oraclecloud.com/pool.name: rook

- name: Install rook operator status
  debug:
    msg: "Rook Operator Installed"
