- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /home/opc/argocd-autopilot

# - name: Download argocd autopilot binary
#   shell: |
#     curl -L --output - https://github.com/argoproj-labs/argocd-autopilot/releases/download/{{argocd_autopilot_version}}/argocd-autopilot-darwin-amd64.tar.gz | tar zx
#   args:
#     chdir: /home/opc/argocd-autopilot

- name: Download argocd autopilot binary
  get_url:
    url: "https://github.com/argoproj-labs/argocd-autopilot/releases/download/{{ argocd_autopilot_version }}/argocd-autopilot-linux-amd64.tar.gz"
    dest: "/home/opc/argocd-autopilot/argocd-autopilot.tar.gz"
    mode: '0644'

- name: Extract argocd autopilot binary
  ansible.builtin.unarchive:
    src: "/home/opc/argocd-autopilot/argocd-autopilot.tar.gz"
    dest: "/home/opc/argocd-autopilot/"
    remote_src: yes

- name: Move binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/home/opc/argocd-autopilot/argocd-autopilot-linux-amd64"
    dest: "/usr/local/bin/argocd-autopilot"
    mode: '0755'
    remote_src: yes

# - name: Download argocd autopilot install
#   shell: |
#     cp ./argocd-autopilot-* /usr/local/bin/argocd-autopilot
#     /usr/local/bin/argocd-autopilot version
#   register: argocd_pilot_install
#   args:
#     chdir: /home/opc/argocd-autopilot

# - name: argocd auto-pilot version
#   debug:
#     msg: "argocd auto-pilot versionversion: {{ argocd_pilot_install.stdout }}"