- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /home/opc/traefik/


- name: Add a traefik helm repository
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts