- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /home/opc/argocd-autopilot

- name: Download argocd autopilot binary & install
  shell: |
    curl -L --output - https://github.com/argoproj-labs/argocd-autopilot/releases/download/{{argocd_autopilot_version}}/argocd-autopilot-darwin-amd64.tar.gz | tar zx
    mv ./argocd-autopilot-* /usr/local/bin/argocd-autopilot
    argocd-autopilot version
  register: argocd_pilot_install

- name: argocd auto-pilot version
  debug:
    msg: "argocd auto-pilot versionversion: {{ argocd_pilot_install.stdout }}"