- name: "Copy deployment check script"
  copy:
    src: "check_deployment.sh"
    dest: "/root/check_deployment.sh"
    mode: "0755"

- name: Install Pip3
  apt:
    name: python3-pip
    update_cache: yes
    state: absent


# - name: Install oci sdk
#   pip:
#     name: 
#       - pyOpenSSL
#       - oci
#     state: absent