- name: Get keycloak admin passord
  shell: |
    admin_password=`kubectl get secret --namespace keycloak keycloak -o go-template='{{index .data "admin-password"|base64decode}}'`
    echo $admin_password
  register: keycloak_admin_password

- name: Create or update a Keycloak client
  community.general.keycloak_client:
    auth_client_id: admin-cli
    auth_keycloak_url: https://keycloak-rancher.{{domain}}/auth
    auth_realm: master
    auth_username: user
    auth_password: "{{keycloak_admin_password.stdout}}"
    state: present
    realm: master
    client_id: test
    