- name: Get keycloak admin passord
  shell: |
    admin_password=`kubectl get secret --namespace keycloak keycloak -o go-template='{{ '{{' }}index .data "admin-password"|base64decode{{ '}}' }}'`
    echo $admin_password
  register: keycloak_admin_password

- name: Create an admin user
  community.general.keycloak_user:
    auth_keycloak_url: https://keycloak-rancher.{{domain}}
    auth_username: user
    auth_password: "{{keycloak_admin_password.stdout}}"
    auth_realm: user
    username: user
    email: rancheradmin1@xyz.com
    enabled: true
    emailVerified: false
    credentials:
        - type: password
          value: "{{keycloak_admin_password.stdout}}"
          temporary: false
    state: present
  register: create_admin_user

# - name: debug
#   debug: 
#     msg: '{{create_admin_user}}'

# - name: Map admin role to a user
#   community.general.keycloak_user_rolemapping:
#     auth_keycloak_url: https://keycloak-rancher.{{domain}}
#     auth_username: user
#     auth_password: "{{keycloak_admin_password.stdout}}"
#     auth_realm: master
#     state: present
#     target_username: rancheradmin
#     roles:
#       - name: role_name1
#         id: role_id1
#       - name: role_name2
#         id: role_id2