- name: Upload ssl cert private key
  copy:
    src: "{{ ansible_ssl_cert_private_key_file }}"
    dest: "/root/.ssh/ssl_cert_private_key.key"
    mode: "0600"

- name: Upload ssl cert file
  copy:
    src: "{{ ansible_ssl_cert_file }}"
    dest: "/root/.ssh/ssl_cert.pem"
    mode: "0600"

# - name: Create ssl secret for keycloak ingress tls
#   shell: |
#     kubectl create ns keycloak
#     kubectl -n keycloak delete secret keycloak-rancher.{{domain}}-tls
#     kubectl create secret tls keycloak-rancher.{{domain}}-tls -n keycloak \
#     --cert=/root/.ssh/ssl_cert.pem \
#     --key=/root/.ssh/ssl_cert_private_key.key
#   ignore_errors: true

- name: Set ssl certificate and key variables
  set_fact:
    ssl_cert: "{{ lookup('file', '/root/.ssh/ssl_cert.pem') }}"
    ssl_cert_key: "{{ lookup('file', '/root/.ssh/ssl_cert_private_key.key) }}"
  
- name: Remove ssl cert private key
  ansible.builtin.file:
    path: /root/.ssh/ssl_cert_private_key.key
    state: absent

- name: Remove ssl cert file
  ansible.builtin.file:
    path: /root/.ssh/ssl_cert.pem
    state: absent


- name: Add a keycloak helm repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Install keycloak
  kubernetes.core.helm:
    name: keycloak
    chart_ref: bitnami/keycloak
    chart_version: 20.0.0
    release_namespace: keycloak
    create_namespace: true
    update_repo_cache: true
    values:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        tls: true
        hostname: "keycloak-rancher.{{domain}}"
        secrets:
          - name: keycloak-rancher.{{domain}}-tls
            key: "{{ssl_cert_key}}"
            certificate: "{{ssl_cert}}"
- name: Wait for deployments in keycloak namespace
  shell: bash /root/check_deployment.sh keycloak