- name: Checking if zone is already present
  oracle.oci.oci_dns_zone_facts:
    compartment_id: "{{compartment_id}}"
    name: "dummy.{{domain}}"
  register: result
  
- name: Dump result
  debug: 
    msg: '{{result}}'

# - name: Zone not found
#   debug:
#     msg: "Zone test.{{domain}} not found"
#   when: result.zones | length == 0

# - name: Zone  found
#   debug:
#     msg: "Zone test.{{domain}}  found"
#   when: result.zones | length != 0

- name: Create zone 
  oracle.oci.oci_dns_zone:
    name: "dummy.{{domain}}"
    compartment_id: "{{compartment_id}}"
    zone_type: PRIMARY
  when: result.zones | length == 0


- name: Update zone_records
  oracle.oci.oci_dns_zone_records:
    zone_name_or_id: "dummy.{{domain}}"
    update_items:
    - domain: "rancher.dummy.{{domain}}"
      rdata: "217.142.250.79"
      rtype: "A"
      ttl: 300
    compartment_id: "{{compartment_id}}"