- name: Get a specific zone
  oracle.oci.oci_dns_zone_facts:
    compartment_id: "{{compartment_id}}"
    name: "test.{{domain}}"
  register: result
  
- name: Dump result
  debug: 
    msg: '{{result}}'