# - name: Deploy SPAR
#   shell: |
#     export SANDBOX_HOSTNAME={{domain}}
#     cd /root/openg2p-deployment/kubernetes/social-payments-account-registry
#     ./install.sh


- name: Copy Deploy folder
  shell: cp -r /root/openg2p-deployment/kubernetes/ /root/openg2p/customization/


- name: "Update spar helm values config"
  template:
    src: "spar/values.yaml.j2"
    dest: "/root/openg2p/customization/kubernetes/social-payments-account-registry/values.yaml"
    mode: '0755'

- name: Deploy SPAR
  shell: |
    export SANDBOX_HOSTNAME={{domain}}
    cd /root/openg2p/customization/kubernetes/social-payments-account-registry
    ./install.sh

- name: Wait for deployments in spar namespace
  shell: bash /root/check_deployment.sh spar

- name: "Update spar update query"
  template:
    src: "spar/update_table.sql.j2"
    dest: "/root/openg2p/customization/kubernetes/social-payments-account-registry/update_table.sql"
    mode: '0755'

- name: Get postgres spar user password
  shell: |
    sparuser_password=`kubectl get secret --namespace postgres postgres-postgresql  -o go-template='{{ '{{' }}index .data "password"|base64decode{{ '}}' }}'`
    echo $sparuser_password
  register: sparuser_password

- name: Update spar login provider
  shell: |
    cd /root/openg2p/customization/kubernetes/social-payments-account-registry/
    kubectl -n postgres exec -i postgres-postgresql-0 -- bash -c 'export PGPASSWORD={{sparuser_password.stdout}} ; psql -U sparuser -d spardb -f -' < update_table.sql