- name: "Upload data loader script"
  template:
    src: "esignet/upload_data_to_mock_esignet.py.j2"
    dest: "/root/openg2p/customization/esignet/upload_data_to_mock_esignet.py"
    mode: '0755'

- name: "Upload sample seed data file"
  copy:
    src: "esignet/sample_data2.csv"
    dest: "/root/openg2p/customization/esignet/sample_data2.csv"
    mode: '0755'

- name: Load sample seed data to esignet
  shell: |
    cd /root/openg2p/customization/esignet/
    python3 upload_data_to_mock_esignet.py /root/openg2p/customization/esignet/sample_data2.csv
  register: data_load

# - name: Dump result
#   debug: 
#     msg: '{{data_load.stdout}}'