#Create a temporary directory for storing values files or other config
- name: install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0700

- name: install kustomize
  get_url:
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v{{ kustomize_version }}/kustomize_kustomize.v{{ kustomize_version }}_linux_amd64
    dest: /usr/local/bin/kustomize
    mode: 0700

- name: Create temporary directory for argo boot
  tempfile:
    state: directory
    suffix: values
  register: argotmpvalues

- name: Create temporary directory for external secrets
  tempfile:
    state: directory
    suffix: values
  register: extsectmpvalues

- name: "create directory for kubeconfig"
  file:
    path: "{{ kubeconfig_location }}"
    state: directory
    recurse: yes

- name: copy kubeconfig
  copy:
    src: "{{ kubeconfig_local_location }}/kubeconfig"
    dest: "{{ kubeconfig_location }}/kubeconfig"

- name: Upload ext secrets bootstrap files
  template:
    src: "templates/{{ item }}.yaml.j2"
    dest: "{{ extsectmpvalues.path }}/{{ item }}.yaml"
  with_items:
    - external-secretstore

- name: Upload argo bootstrap files
  template:
    src: "templates/{{ item }}.yaml.j2"
    dest: "{{ argotmpvalues.path }}/{{ item }}.yaml"
  with_items:
    - argo-cm
    - argo-gitlab
    - argo-root-app
    - argo-service-acct-patch
    - argocd-lovely-plugin
    - kustomization
    - namespace
    - vault-service-account-etc
    - vault-env
    - netclient

- name: Install external-secrets
  shell: |
    helm repo add external-secrets https://charts.external-secrets.io
    helm --kubeconfig {{ kubeconfig_location }}/kubeconfig upgrade --install external-secrets external-secrets/external-secrets --version {{ external_secrets_version }} -n {{ external_secrets_namespace }} --create-namespace --set installCRDs=true

- name: Try clustersecretstore create until successful
  shell: kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig apply -n {{ external_secrets_namespace }} -f {{ extsectmpvalues.path }}/external-secretstore.yaml
  register: clustersecretstore
  until: clustersecretstore is not failed
  retries: 30
  delay: 5

- name: Install ArgoCD
  shell: |
    kustomize build {{ argotmpvalues.path }} > {{ argotmpvalues.path }}/argocd-deploy.yaml
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig apply -f {{ argotmpvalues.path }}/argocd-deploy.yaml
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig apply -f {{ argotmpvalues.path }}/argo-root-app.yaml
