- name: Add a reloader helm repository
  kubernetes.core.helm_repository:
    name: stakater
    repo_url: https://stakater.github.io/stakater-charts

- name: Install reloader
  kubernetes.core.helm:
    name: reloader
    chart_ref: stakater/reloader
    chart_version: "{{reloader_chart_version}}"
    release_namespace: istio-system
    create_namespace: true
    update_repo_cache: true
    values:
      reloader:
        watchGlobally: false
