- name: Add a longhorn helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{longhorn_chart_version}}"
    release_namespace: longhorn-system
    create_namespace: true
    update_repo_cache: true
    values:
      persistence:
        defaultClassReplicaCount: "{{ longhorn_default_replica_count |default('3') }}"
      service:
        ui:
          type: ClusterIP