- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /home/opc/certmanager

- name: Add a certmanager helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Add a ACME webhook for Oracle Cloud Infrastructure helm repository
  kubernetes.core.helm_repository:
    name: cert-manager-webhook-oci
    repo_url: https://dn13.gitlab.io/cert-manager-webhook-oci

- name: Install certmanager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true
    values:
      installCRDs: true

- name: Install cert-manager-webhook-oci
  kubernetes.core.helm:
    name: cert-manager-webhook-oci
    chart_ref: cert-manager-webhook-oci/cert-manager-webhook-oci
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true

- name: "Update certmanager templates"
  template:
    src: "cert-manager/{{item}}.j2"
    dest: "/home/opc/certmanager/{{item}}"
    mode: '0755'
  with_items:
    - clusterissuer.yaml

- name: Create k8s objects for certmanager
  kubernetes.core.k8s:
    state: present
    src: /home/opc/certmanager/{{item}}
  with_items:
    - clusterissuer.yaml
