- name: Debug Message
  debug:
    msg: "Generating oke kube config"

- name: Generate kube config for oke k8s cluster
  shell: |
    oci ce cluster create-kubeconfig --cluster-id {{oke_k8s_cluster_id}} --file ~/.kube/config --region {{region}} --token-version 2.0.0  --kube-endpoint PRIVATE_ENDPOINT
    chmod 600 ~/.kube/config

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{item}}"
    api_version: v1
    kind: Namespace
    state: present
  with_items:
    - argocd