- name: Create cleanup directory
  file:
    path: "/root/sunbird-rc/cleanup"
    state: directory
    mode: '0755'

- name: Copy cleanup script
  template:
    src: uninstall.j2
    dest: "/root/sunbird-rc/cleanup/uninstall.sh"
    mode: '0755'


- name: Uninstall longhorn
  shell: |
    kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag
  ignore_errors: true

- name: Uninstall postgres
  shell: |
    kubectl -n sunbird-rc delete cluster.postgresql.cnpg.io/postgres-cluster
  ignore_errors: true
  when: not create_registry_db 

- name: Clean up vault
  file:
    path: /root/sunbird-rc/customization/vault/vault_init.done
    state: absent

- name: Uninstall applications
  shell: /root/sunbird-rc/cleanup/uninstall.sh {{item}}
  with_items:
    - sunbird-rc
    - cnpg-system
    - vault   
    - longhorn-system
  ignore_errors: true


- name: Remove zone records
  oracle.oci.oci_dns_rrset:
    zone_name_or_id: "{{domain}}"
    domain: "{{item}}.{{domain}}"
    rtype: "A"
    state: absent
  with_items:
    - sbrc
    - sbrciam
    - sbrcfs

- name: Uninstall istio service mesh
  shell: |
    export PATH=/root/istio-1.21.0/bin:$PATH
    istioctl uninstall -y --purge
    kubectl delete ns istio-system
