- name: "Copy rancher terraform files"
  template:
    src: "rancher.j2"
    dest: "/root/rancher/terraform/rancher.tf"
    mode: "0755"

- name: "Execute rancher terraform"
  shell: |
    cd /root/rancher/terraform/
    tofu init
    tofu apply -auto-approve -refresh=false

- name: "Running Register Cluster Command"
  shell: |
    cd /root/rancher/terraform/
    output_json=$(tofu output -json)
    command_output=$(echo "$output_json" | jq -r '.cluster_registration_command.value')
    kubectl apply -f ${command_output}