- name: "Copy rancher terraform files"
  template:
    src: "rancher.j2"
    dest: "/root/rancher/terraform/rancher.tf"
    mode: "0755"

- name: "Copy rancher bootstrap module terraform files"
  template:
    src: "bootstrap.j2"
    dest: "/root/rancher/terraform/bootstrap/bootstrap.tf"
    mode: "0755"

- name: "Copy terraform template files"
  template:
    src: "clusteragent.yaml.tmpl.j2"
    dest: "/root/rancher/terraform/templates/clusteragent.yaml.tmpl"
    mode: "0755"

- name: "Execute rancher terraform"
  shell: |
    cd /root/rancher/terraform/
    tofu init
    tofu apply -auto-approve

# - name: "Running Register Cluster Command"
#   shell: |
#     cd /root/rancher/terraform/
#     output_json=$(tofu output -json)
#     command_output=$(echo "$output_json" | jq -r '.cluster_registration_command.value')
#     eval "${command_output}"