- hosts: operator
  become: true
  environment:
    OCI_CLI_AUTH: "instance_principal"
    OCI_ANSIBLE_AUTH_TYPE: "instance_principal"
    KUBECONFIG: "/home/opc/.kube/config"
  roles:
    - generic.iac.bootstrap_k8s
    # - generic.iac.rook_deploy
    - generic.iac.minio_deploy
    # - generic.iac.cilium_client


