- hosts: bastion
  become: true
  roles:
    - mojaloop.iac.bastion_common
    - mojaloop.iac.netclient
    - mojaloop.iac.haproxy

- hosts: master
  become: true
  roles:
    - mojaloop.iac.k3s_common
    - mojaloop.iac.k3s_master

- hosts: agent
  become: true
  roles:
    - mojaloop.iac.k3s_common
    - mojaloop.iac.k3s_worker

- hosts: bastion
  become: true
  roles:
    - geerlingguy.k8s.helm
    - mojaloop.iac.argocd

- name: Create Test Harness
  import_playbook: test_harness_deploy.yaml
