- hosts: netmaker
  become: true
  roles:
    - mojaloop.iac.docker
    - mojaloop.iac.netmaker

- hosts: bastion
  become: true
  roles:
    - mojaloop.iac.netclient

- hosts: docker
  become: true
  roles:
    - mojaloop.iac.vault