- name: Deploy Logging
  shell: |
    export SANDBOX_HOSTNAME={{domain}}
    cd /root/sunbird-rc-deployment/kubernetes/logging
    ./install.sh

## Temporarliy disabled
# - name: Wait for deployments in cattle-logging-system namespace
#   shell: bash /root/check_deployment.sh cattle-logging-system
